# Generated by Django 4.0 on 2022-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('titulo', models.CharField(max_length=50,
                 primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
