# Generated by Django 4.0 on 2022-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrenos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ManyToManyField(blank=True, to='estrenos.Usuario'),
        ),
    ]
