# Generated by Django 4.0 on 2022-05-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estrenos', '0002_remove_pelicula_usuario_pelicula_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
